version: '3'

services:
  web:
    image: xordk/cj-comingsoon:latest
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - SECRET_KEY=
